version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend